version: '3.8'
# run with: docker-compose --env-file .env up -d --build

services:

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    image: mysql:8.1
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - .docker/mysql_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - persistent:/var/lib/mysql
    networks:
      - bache-finder-network
  
  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - bache-finder-network

  ####################################################################################################
  # backend app
  ####################################################################################################
  # app:
  #   build:
  #     context: .docker/php-apache
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - .:/var/www/html:cached
  #   networks:
  #     - bache-finder-network
  #   command: >
  #     /bin/sh -c "php artisan storage:link && apache2-foreground"

  ####################################################################################################
  #  nginx
  ####################################################################################################
  nginx:
    image: nginx:stable-alpine
    ports:
        - '8001:80'
    links:
        - php:php
    volumes:
        - .:/var/www/html
        - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
        - ./.docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
        - php
        - db
    networks:
        - bache-finder-network
    restart: always
    tty: true

  ####################################################################################################
  # php
  ####################################################################################################
  php:
    build:
        context: ./.docker/php
        dockerfile: Dockerfile
    volumes:
        - .:/var/www/html
    ports:
        - '${FORWARD_PHP_PORT:-9000}:9000'
    networks:
        - bache-finder-network
    depends_on:
        - db
    restart: unless-stopped
#   command: >
#      /bin/sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"
    tty: true
    links:
        - db:db

####################################################################################################
networks:
  bache-finder-network:
    external: true

volumes:
  persistent:
    driver: local
